### ISSUE TITLE
Suggestion: Languages and technogolies

### ISSUE THREAD

**Issue by TylerAustinW** [Honzoraptor31415/Portfolio#1]
I found your portfolio from `The Programmers Hangout` Discord, and thought I'd suggest something for the Language and technologies (which is also misspelled on your site) but the suggestion i had in mind was to have that slide in like the rest, when the user scrolls, keeps everything the same and nice and fluid, other then that. impressive. 

reference: https://github.com/Honzoraptor31415/Portfolio/blob/16b3ecac5520b62d78e71056aa87ae80bfe9faca/src/components/Home.tsx#L88

**Comment by Honzoraptor31415** [comment]
Oh yeah thanks so much.

lol "technogolies"
